version: "3.8"

services:
  db:
    image: mariadb
    ports:
      - 3061:3061
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  db_data:
