version: "3.8"

services:
  db:
    image: mariadb
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  db_data:
