# Generated by Django 4.1.1 on 2022-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='allowed_width',
        ),
        migrations.AddField(
            model_name='tier',
            name='can_get_original_link',
            field=models.BooleanField(default=False, verbose_name='Permission to fetch an original image link'),
        ),
    ]
