# Generated by Django 4.1.1 on 2022-09-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thumbnails.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=thumbnails.models._get_original_image_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=thumbnails.models._get_thumbnail_image_path)),
                ('original_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thumbnails.image')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='thumbnails.thumbnailsize')),
            ],
        ),
    ]
