# Generated by Django 4.1.1 on 2022-09-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
    ]
